### ISSUE TITLE
FXmaster does not play well with Dungeon Draw

### ISSUE THREAD

**Issue by Opius134** [gambit07/fxmaster#567]
### Expected Behavior

Checking off effects on the filter effects management window and hitting save should apply those filters to the canvas. 

### Current Behavior

When the module Dungeon Draw (https://github.com/mcglincy/dungeondraw-foundry-vtt) is installed and active, only the Fog and Underwater filters work. All other filters kick off an error in the console window and produce no visible change. 

### Steps to Reproduce

1) Activate both FXMaster and Dungeon Draw
2) Toggle a filter effect in the dilter effects management window (aside from Underwater and Fog, those seem to work)
3) Hit save

### Context

![image](https://github.com/ghost-fvtt/fxmaster/assets/100728089/4653034a-4b18-451f-bf18-228df971c369)

Uncaught (in promise) TypeError: Class constructor Ti cannot be invoked without 'new'
    at new t (pixi-filters.min.js:8:7046)
    at new <anonymous> (filter.js:14:7)
    at new <anonymous> (fading-filter.js:15:10)
    at new BloomFilter (bloom.js:3:8)
    at #r (filter-manager.js:80:27)
    at Object.fn (filter-manager.js:217:14)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13653:13)
    at foundry.js:13626:43

  | t | @ | pixi-filters.min.js:8
  | (anonymous) | @ | filter.js:14
  | (anonymous) | @ | fading-filter.js:15
  | BloomFilter | @ | bloom.js:3
  | #r | @ | filter-manager.js:80
  | (anonymous) | @ | filter-manager.js:217
  | #call | @ | foundry.js:730
  | callAll | @ | foundry.js:687
  | callback | @ | foundry.js:13653
  | (anonymous) | @ | foundry.js:13626
  | #handleUpdateDocuments | @ | foundry.js:13626
  | await in #handleUpdateDocuments (async) |   |  
  | _updateDocuments | @ | foundry.js:13373
  | await in _updateDocuments (async) |   |  
  | update | @ | commons.js:8583
  | await in update (async) |   |  
  | updateDocuments | @ | commons.js:7907
  | update | @ | commons.js:8004
  | setFlag | @ | commons.js:8201
  | resetFlag | @ | utils.js:19
  | _updateObject | @ | filter-effects-management.js:74
  | _onSubmit | @ | foundry.js:6546
  | _onSubmit | @ | base-form.js:93

### Version

4.0.2

### Foundry VTT Version

v11.306

### Operating System

Windows (hosted on ubuntu)

### Browser / App

Chrome

### Game System

DnD5e 2.2.2

### Relevant Modules

FXMaster, Dungeon Draw

**Comment by ghost91-** [comment]
I’ll take a look and see if there’s anything I can do about it.
